import { RawSheetData, ParsedWorkbook } from '../types';

export interface SampleDatasetOption {
  id: string;
  title: string;
  description: string;
  fileName: string;
  fileType: 'csv' | 'xlsx';
  tags: string[];
  workbook: ParsedWorkbook;
}

const SAMPLE_1_ROWS: Record<string, unknown>[] = [
  {
    'Invoice #': 'INV-2024-001',
    'Sale Date': '2024-07-02',
    'Account Rep': 'Sarah Jenkins',
    'Client Organization': 'Acme Corp',
    'Product Line': 'Software',
    'Gross Revenue': '$4,500.00',
    'Promo Discount': '$0.00',
    'Payment Stage': 'Closed Won',
    'Commission Override': '',
    'Notes': 'Annual software license renewed',
  },
  {
    'Invoice #': 'INV-2024-002',
    'Sale Date': '2024-07-05',
    'Account Rep': 'David Chen',
    'Client Organization': 'Apex Logistics',
    'Product Line': 'Enterprise',
    'Gross Revenue': '$16,200.00',
    'Promo Discount': '$500.00',
    'Payment Stage': 'Closed Won',
    'Commission Override': '',
    'Notes': 'Multi-location rollout tier 4',
  },
  {
    'Invoice #': 'INV-2024-003',
    'Sale Date': '2024-07-08',
    'Account Rep': 'Elena Rostova',
    'Client Organization': 'Starlight Media',
    'Product Line': 'Services',
    'Gross Revenue': '$3,200.00',
    'Promo Discount': '$200.00',
    'Payment Stage': 'Paid',
    'Commission Override': '9%',
    'Notes': 'Onboarding & integration package with custom rate',
  },
  {
    'Invoice #': 'INV-2024-004',
    'Sale Date': '2024-07-12',
    'Account Rep': 'Marcus Vance',
    'Client Organization': 'BlueWave Health',
    'Product Line': 'Hardware',
    'Gross Revenue': '$8,450.00',
    'Promo Discount': '$450.00',
    'Payment Stage': 'Closed Won',
    'Commission Override': '',
    'Notes': 'Terminal hardware bundle',
  },
  {
    'Invoice #': 'INV-2024-005',
    'Sale Date': '2024-07-16',
    'Account Rep': 'Sarah Jenkins',
    'Client Organization': 'Vertex Labs',
    'Product Line': 'Consulting',
    'Gross Revenue': '$6,000.00',
    'Promo Discount': '$0.00',
    'Payment Stage': 'Closed Won',
    'Commission Override': '',
    'Notes': 'Architecture advisory sprint',
  },
  {
    'Invoice #': 'INV-2024-006',
    'Sale Date': '2024-07-20',
    'Account Rep': 'David Chen',
    'Client Organization': 'Zenith Retail',
    'Product Line': 'Software',
    'Gross Revenue': '$9,800.00',
    'Promo Discount': '$800.00',
    'Payment Stage': 'Paid',
    'Commission Override': '',
    'Notes': 'Cloud analytics suite',
  },
  {
    'Invoice #': 'INV-2024-007',
    'Sale Date': '2024-07-25',
    'Account Rep': 'Elena Rostova',
    'Client Organization': 'Summit Financial',
    'Product Line': 'Enterprise',
    'Gross Revenue': '$22,500.00',
    'Promo Discount': '$1,500.00',
    'Payment Stage': 'Closed Won',
    'Commission Override': '',
    'Notes': 'Enterprise full deployment (Qualifies for high-ticket bonus)',
  },
  {
    'Invoice #': 'INV-2024-008',
    'Sale Date': '2024-07-28',
    'Account Rep': 'Marcus Vance',
    'Client Organization': 'Horizon Tech',
    'Product Line': 'Services',
    'Gross Revenue': '$1,250.00',
    'Promo Discount': '$0.00',
    'Payment Stage': 'Paid',
    'Commission Override': '',
    'Notes': 'Standard SLA maintenance add-on',
  },
  {
    'Invoice #': 'INV-2024-009',
    'Sale Date': '2024-08-03',
    'Account Rep': 'Sarah Jenkins',
    'Client Organization': 'Pioneer Energy',
    'Product Line': 'Software',
    'Gross Revenue': '$12,400.00',
    'Promo Discount': '$400.00',
    'Payment Stage': 'Closed Won',
    'Commission Override': '',
    'Notes': 'Energy dashboard platform',
  },
  {
    'Invoice #': 'INV-2024-0010',
    'Sale Date': '2024-08-10',
    'Account Rep': 'David Chen',
    'Client Organization': 'Beacon Global',
    'Product Line': 'Hardware',
    'Gross Revenue': '$4,900.00',
    'Promo Discount': '$100.00',
    'Payment Stage': 'Closed Won',
    'Commission Override': '',
    'Notes': 'Edge computing sensors',
  },
  {
    'Invoice #': 'INV-2024-0011',
    'Sale Date': '2024-08-15',
    'Account Rep': 'Elena Rostova',
    'Client Organization': 'GreenField Bio',
    'Product Line': 'Consulting',
    'Gross Revenue': '$7,800.00',
    'Promo Discount': '$300.00',
    'Payment Stage': 'Paid',
    'Commission Override': '',
    'Notes': 'Compliance and data governance audit',
  },
  {
    'Invoice #': 'INV-2024-0012',
    'Sale Date': '2024-08-22',
    'Account Rep': 'Marcus Vance',
    'Client Organization': 'Nova Logistics',
    'Product Line': 'Software',
    'Gross Revenue': '$14,000.00',
    'Promo Discount': '$1,000.00',
    'Payment Stage': 'Closed Won',
    'Commission Override': '',
    'Notes': 'Route optimization module',
  }
];

const SAMPLE_2_ROWS: Record<string, unknown>[] = [
  {
    'Trans_ID': 'TXN-8801',
    'Date_Created': '08/01/2024',
    'Sales_Agent': 'Alex Rivera',
    'Customer_Name': 'Quantum Dynamics',
    'Department': 'Software',
    'Total_Price': '$5,400.00',
    'Discount': '$0.00',
    'Status': 'Closed Won',
    'Rate_Override': '',
    'Comments': 'Standard enterprise license',
  },
  {
    'Trans_ID': 'TXN-8802',
    'Date_Created': '08/04/2024',
    'Sales_Agent': 'Jordan Taylor',
    'Customer_Name': 'Solaris Media',
    'Department': 'Services',
    'Total_Price': '$8,900.00',
    'Discount': '$400.00',
    'Status': 'Paid',
    'Rate_Override': '',
    'Comments': 'Design sprint',
  },
  {
    'Trans_ID': 'TXN-8803',
    'Date_Created': '08/08/2024',
    'Sales_Agent': '', // Missing rep (flagged)
    'Customer_Name': 'Vanguard Security',
    'Department': 'Hardware',
    'Total_Price': '$3,600.00',
    'Discount': '$0.00',
    'Status': 'Closed Won',
    'Rate_Override': '',
    'Comments': 'Direct web order - no rep assigned',
  },
  {
    'Trans_ID': 'TXN-8804',
    'Date_Created': '08/12/2024',
    'Sales_Agent': 'Alex Rivera',
    'Customer_Name': 'Titan Manufacturing',
    'Department': 'Software',
    'Total_Price': '-$1,200.00', // Refund (flagged)
    'Discount': '$0.00',
    'Status': 'Refunded',
    'Rate_Override': '',
    'Comments': 'Partial return of unused seats',
  },
  {
    'Trans_ID': 'TXN-8801', // Duplicate ID with row 1 (flagged)
    'Date_Created': '08/15/2024',
    'Sales_Agent': 'Morgan Lee',
    'Customer_Name': 'Quantum Dynamics',
    'Department': 'Consulting',
    'Total_Price': '$4,200.00',
    'Discount': '$200.00',
    'Status': 'Closed Won',
    'Rate_Override': '',
    'Comments': 'Follow up engagement with duplicate order ID',
  },
  {
    'Trans_ID': 'TXN-8806',
    'Date_Created': '08/19/2024',
    'Sales_Agent': 'Jordan Taylor',
    'Customer_Name': 'Echo Robotics',
    'Department': 'Enterprise',
    'Total_Price': '$28,000.00',
    'Discount': '$2,000.00',
    'Status': 'Closed Won',
    'Rate_Override': '',
    'Comments': 'Fleet automation license (Big deal + bonus)',
  },
  {
    'Trans_ID': 'TXN-8807',
    'Date_Created': '08/25/2024',
    'Sales_Agent': 'Morgan Lee',
    'Customer_Name': 'Apex Healthcare',
    'Department': 'Services',
    'Total_Price': '$11,500.00',
    'Discount': '$500.00',
    'Status': 'Paid',
    'Rate_Override': '14%', // High rate override
    'Comments': 'Special contract rate approved by VP',
  }
];

const SAMPLE_3_MESSY_ROWS: Record<string, unknown>[] = [
  {
    'Order #': 'ORD-9001',
    'Date of Sale': '2024-08-01',
    'Account Executive': ' \uFEFF Sarah Jenkins \u200B ', // Whitespace & zero-width chars
    'Client Name': 'Acme Global',
    'Line of Business': 'Software',
    'Gross Sales ($)': '$6,500.00',
    'Promo Disc': '$0.00',
    'Disposition': 'Closed Won',
    'Split %': '8%',
    'Remarks': 'Whitespace trimmed from rep name',
  },
  {
    'Order #': 'ORD-9002',
    'Date of Sale': '15-Aug-2024', // Textual month format
    'Account Executive': 'David Chen',
    'Client Name': 'Nova Tech',
    'Line of Business': 'Enterprise',
    'Gross Sales ($)': '18.450,00 €', // European number format with currency
    'Promo Disc': '$450.00',
    'Disposition': 'Closed Won',
    'Split %': '',
    'Remarks': 'European decimal format parsed cleanly',
  },
  {
    'Order #': 'ORD-9003',
    'Date of Sale': '08/20/2024', // US date format
    'Account Executive': 'N/A', // Placeholder rep -> Flagged as missing
    'Client Name': 'Omni Health',
    'Line of Business': 'Hardware',
    'Gross Sales ($)': '$3,200.00',
    'Promo Disc': '$0.00',
    'Disposition': 'Closed Won',
    'Split %': '',
    'Remarks': 'Placeholder rep flagged with MISSING_SALES_REP error',
  },
  {
    'Order #': 'ORD-9004',
    'Date of Sale': '2024-02-31', // Impossible calendar date -> Flagged
    'Account Executive': 'Elena Rostova',
    'Client Name': 'Apex Group',
    'Line of Business': 'Services',
    'Gross Sales ($)': '$5,000.00',
    'Promo Disc': '$0.00',
    'Disposition': 'Closed Won',
    'Split %': '',
    'Remarks': 'Invalid date flagged with UNPARSEABLE_DATE error',
  },
  {
    'Order #': 'ORD-9005',
    'Date of Sale': '08/22/2024',
    'Account Executive': 'Marcus Vance',
    'Client Name': 'Starlight Media',
    'Line of Business': 'Software',
    'Gross Sales ($)': '($1,500.00)', // Accounting negative refund
    'Promo Disc': '$0.00',
    'Disposition': 'Refunded',
    'Split %': '',
    'Remarks': 'Accounting parenthesis refund ($1,500) -> -$1,500',
  },
  {
    'Order #': 'ORD-9001', // Duplicate Order # with Row 1 -> Flagged
    'Date of Sale': '08/25/2024',
    'Account Executive': 'Sarah Jenkins',
    'Client Name': 'Acme Global',
    'Line of Business': 'Consulting',
    'Gross Sales ($)': '$4,200.00',
    'Promo Disc': '$200.00',
    'Disposition': 'Closed Won',
    'Split %': '',
    'Remarks': 'Duplicate order ID flagged with source row reference',
  },
  {
    'Order #': '', // Missing Order # -> Generated & flagged
    'Date of Sale': '08/28/2024',
    'Account Executive': 'David Chen',
    'Client Name': 'Zenith Logistics',
    'Line of Business': 'Hardware',
    'Gross Sales ($)': '$9,800.00',
    'Promo Disc': '$12,000.00', // Discount > Gross -> Flagged
    'Disposition': 'Closed Won',
    'Split %': '',
    'Remarks': 'Discount exceeds gross sale, resulting in negative net',
  },
  {
    'Order #': 'ORD-9008',
    'Date of Sale': '08/29/2024',
    'Account Executive': 'Elena Rostova',
    'Client Name': 'Alpha Dynamics',
    'Line of Business': 'Software',
    'Gross Sales ($)': 'TBD - Contact Sales', // Unparseable gross -> Flagged
    'Promo Disc': '$0.00',
    'Disposition': 'Pending',
    'Split %': '',
    'Remarks': 'Non-numeric gross amount flagged with error',
  }
];

export const SAMPLE_DATASETS: SampleDatasetOption[] = [
  {
    id: 'sample_q3_tech_sales',
    title: 'Small Business Q3 Tech Sales (12 Deals)',
    description: 'Clean real-world dataset with 4 reps (Sarah, David, Elena, Marcus), tiered products ($1.2k - $22.5k), and category bonuses.',
    fileName: 'Q3_Sales_Commission_Export_2024.xlsx',
    fileType: 'xlsx',
    tags: ['Clean', 'Multi-Rep', 'Tiered'],
    workbook: {
      fileName: 'Q3_Sales_Commission_Export_2024.xlsx',
      fileSize: 14200,
      fileType: 'xlsx',
      sheets: [
        {
          sheetName: 'Q3_Closed_Deals',
          headers: [
            'Invoice #',
            'Sale Date',
            'Account Rep',
            'Client Organization',
            'Product Line',
            'Gross Revenue',
            'Promo Discount',
            'Payment Stage',
            'Commission Override',
            'Notes',
          ],
          rows: SAMPLE_1_ROWS,
          totalRowCount: SAMPLE_1_ROWS.length,
        },
      ],
      activeSheetName: 'Q3_Closed_Deals',
      uploadedAt: new Date().toISOString(),
    },
  },
  {
    id: 'sample_anomalies_validation',
    title: 'Sales Export with Edge Cases & Refunds (7 Deals)',
    description: 'Demonstrates validation alerts: unassigned rep, negative return/refund, duplicate transaction ID, and custom rate override.',
    fileName: 'August_Agency_Commission_Audit.csv',
    fileType: 'csv',
    tags: ['Validation Alerts', 'Refunds', 'Duplicate Check'],
    workbook: {
      fileName: 'August_Agency_Commission_Audit.csv',
      fileSize: 6800,
      fileType: 'csv',
      sheets: [
        {
          sheetName: 'August_Export',
          headers: [
            'Trans_ID',
            'Date_Created',
            'Sales_Agent',
            'Customer_Name',
            'Department',
            'Total_Price',
            'Discount',
            'Status',
            'Rate_Override',
            'Comments',
          ],
          rows: SAMPLE_2_ROWS,
          totalRowCount: SAMPLE_2_ROWS.length,
        },
      ],
      activeSheetName: 'August_Export',
      uploadedAt: new Date().toISOString(),
    },
  },
  {
    id: 'sample_messy_real_world',
    title: 'Intentionally Messy Real-World Export (8 Deals)',
    description: 'Demonstrates edge cases: zero-width whitespace, textual dates (15-Aug-2024), European decimals (€18.450,00), accounting negatives ($1,500), impossible dates (Feb 31), unparseable text (TBD), and discount > gross.',
    fileName: 'Messy_Raw_CRM_Export_Q3.csv',
    fileType: 'csv',
    tags: ['Messy Data', 'Whitespaces', 'European Decimals', 'Date Edge Cases'],
    workbook: {
      fileName: 'Messy_Raw_CRM_Export_Q3.csv',
      fileSize: 8400,
      fileType: 'csv',
      sheets: [
        {
          sheetName: 'Raw_CRM_Dump',
          headers: [
            'Order #',
            'Date of Sale',
            'Account Executive',
            'Client Name',
            'Line of Business',
            'Gross Sales ($)',
            'Promo Disc',
            'Disposition',
            'Split %',
            'Remarks',
          ],
          rows: SAMPLE_3_MESSY_ROWS,
          totalRowCount: SAMPLE_3_MESSY_ROWS.length,
        },
      ],
      activeSheetName: 'Raw_CRM_Dump',
      uploadedAt: new Date().toISOString(),
    },
  },
];
